/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CA1;

import java.io.*;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajka
 */
public class RentalMenu extends javax.swing.JFrame {

    private RentalSystem RS = new RentalSystem();
    private long startTime = System.nanoTime();

    /**
     * Creates new form RentalMenu
     */
    public RentalMenu() {
        initComponents();
        
        
        // to display first comic and rentee when GUI starts
        int index = 0;
        int Comicsize = RS.getSizeOfComic();

        Comic displayComic = RS.searchComicByIndex(index);
        txtISBN.setText(displayComic.getISBN());
        txtTitle.setText(displayComic.getTitle());
        txtRentalCost.setText(displayComic.getRentalFee());
        txtDeposit.setText(displayComic.getDepositFee());
        txtInfo.setText(displayComic.getInfo());
        lblComic.setText("Comic " + (index + 1) + " of " + Comicsize);

        int Membersize = RS.getSizeOfMember();

        Rentee displayMember = RS.searchMemberByIndex(index);
        txtMember.setText(displayMember.getID());
        txtName.setText(displayMember.getName());
        DefaultTableModel tableModel = (DefaultTableModel) tableLoan.getModel();

        for (Comic comic : displayMember.getComicsLoaned())
        {
            Object[] rowData = new Object[4];
            rowData[0] = comic.getISBN();
            rowData[1] = comic.getTitle();
            rowData[2] = comic.getRentalFee();
            rowData[3] = comic.getDepositFee();
            tableModel.addRow(rowData);
        }

        lblRentee.setText("Rentee " + (index + 1) + " of " + Membersize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panelComic = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        btnNextComic = new javax.swing.JButton();
        btnPreviousComic = new javax.swing.JButton();
        txtISBN = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JTextField();
        txtRentalCost = new javax.swing.JTextField();
        panelRentee = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnNextMember = new javax.swing.JButton();
        btnPreviousMember = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLoan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        panelMessage = new javax.swing.JPanel();
        btnStats = new javax.swing.JButton();
        txtClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        panelSearch = new javax.swing.JPanel();
        radioISBN = new javax.swing.JRadioButton();
        radioMember = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        lblRentee = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblComic = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Comic Rental System");

        panelComic.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ISBN-13:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Title:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Daily Rental Cost: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Deposit:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Additional Information:");

        txtTitle.setEditable(false);
        txtTitle.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        txtInfo.setEditable(false);
        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        txtInfo.setRows(5);
        jScrollPane3.setViewportView(txtInfo);

        btnNextComic.setBackground(new java.awt.Color(98, 102, 239));
        btnNextComic.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNextComic.setText("Next");
        btnNextComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextComicActionPerformed(evt);
            }
        });

        btnPreviousComic.setBackground(new java.awt.Color(98, 102, 239));
        btnPreviousComic.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPreviousComic.setText("Previous");
        btnPreviousComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousComicActionPerformed(evt);
            }
        });

        txtISBN.setEditable(false);
        txtISBN.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        txtDeposit.setEditable(false);
        txtDeposit.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        txtRentalCost.setEditable(false);
        txtRentalCost.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelComicLayout = new javax.swing.GroupLayout(panelComic);
        panelComic.setLayout(panelComicLayout);
        panelComicLayout.setHorizontalGroup(
            panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComicLayout.createSequentialGroup()
                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelComicLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnPreviousComic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextComic, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComicLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(panelComicLayout.createSequentialGroup()
                                    .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelComicLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelComicLayout.createSequentialGroup()
                                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtRentalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelComicLayout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        panelComicLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNextComic, btnPreviousComic});

        panelComicLayout.setVerticalGroup(
            panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComicLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComicLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComicLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRentalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPreviousComic)
                    .addComponent(btnNextComic, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelComicLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );

        panelComicLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNextComic, btnPreviousComic});

        panelRentee.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("List of Loans:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Member-ID:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Name:");

        txtMember.setEditable(false);
        txtMember.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        btnNextMember.setBackground(new java.awt.Color(102, 102, 255));
        btnNextMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNextMember.setText("Next");
        btnNextMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextMemberActionPerformed(evt);
            }
        });

        btnPreviousMember.setBackground(new java.awt.Color(102, 102, 255));
        btnPreviousMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPreviousMember.setText("Previous");
        btnPreviousMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousMemberActionPerformed(evt);
            }
        });

        tableLoan.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tableLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Rental Per Day", "Deposit Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLoan.getTableHeader().setResizingAllowed(false);
        tableLoan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableLoan);

        javax.swing.GroupLayout panelRenteeLayout = new javax.swing.GroupLayout(panelRentee);
        panelRentee.setLayout(panelRenteeLayout);
        panelRenteeLayout.setHorizontalGroup(
            panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRenteeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRenteeLayout.createSequentialGroup()
                        .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addGroup(panelRenteeLayout.createSequentialGroup()
                                .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelRenteeLayout.createSequentialGroup()
                                        .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelRenteeLayout.createSequentialGroup()
                        .addComponent(btnPreviousMember, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextMember)
                        .addGap(19, 19, 19))))
        );

        panelRenteeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNextMember, btnPreviousMember});

        panelRenteeLayout.setVerticalGroup(
            panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRenteeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreviousMember, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextMember))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRenteeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNextMember, btnPreviousMember});

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Search");

        panelMessage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnStats.setBackground(new java.awt.Color(51, 51, 255));
        btnStats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStats.setText("Get Earning Stats");
        btnStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsActionPerformed(evt);
            }
        });

        txtClear.setBackground(new java.awt.Color(51, 0, 255));
        txtClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClear.setText("Clear Message");
        txtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClearActionPerformed(evt);
            }
        });

        txtMessage.setEditable(false);
        txtMessage.setColumns(20);
        txtMessage.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        txtMessage.setRows(5);
        jScrollPane2.setViewportView(txtMessage);

        javax.swing.GroupLayout panelMessageLayout = new javax.swing.GroupLayout(panelMessage);
        panelMessage.setLayout(panelMessageLayout);
        panelMessageLayout.setHorizontalGroup(
            panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMessageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMessageLayout.createSequentialGroup()
                        .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtClear)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelMessageLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnStats, txtClear});

        panelMessageLayout.setVerticalGroup(
            panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClear))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelMessageLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnStats, txtClear});

        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(radioISBN);
        radioISBN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioISBN.setText("Comic by ISBN-13");

        buttonGroup1.add(radioMember);
        radioMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioMember.setText("Rentee by MemberID");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch1.setBackground(new java.awt.Color(0, 153, 51));
        btnSearch1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(radioISBN)
                        .addGap(40, 40, 40)
                        .addComponent(radioMember))
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                    .addContainerGap(472, Short.MAX_VALUE)
                    .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioISBN)
                    .addComponent(radioMember))
                .addGap(36, 36, 36)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                    .addContainerGap(173, Short.MAX_VALUE)
                    .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        lblRentee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRentee.setText("Rentee 1 of 4");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("System Message");

        btnSave.setBackground(new java.awt.Color(255, 51, 51));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setText("Save & Exit");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblComic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblComic.setText("Comic 1 of 6");

        btnAdmin.setBackground(new java.awt.Color(0, 204, 255));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblComic, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelComic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRentee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRentee, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(panelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAdmin)
                                .addGap(39, 39, 39)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(458, 458, 458))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdmin, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRentee)
                    .addComponent(lblComic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelComic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRentee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdmin))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdmin, btnSave});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextComicActionPerformed

        //to scroll to next comic
        
        String ISBN = txtISBN.getText();
        int index = RS.getComicIndex(ISBN);

        int size = RS.getSizeOfComic();
        if (index < size - 1)
        {
            index++;
            Comic displayComic = RS.searchComicByIndex(index);
            txtISBN.setText(displayComic.getISBN());
            txtTitle.setText(displayComic.getTitle());
            txtRentalCost.setText(displayComic.getRentalFee());
            txtDeposit.setText(displayComic.getDepositFee());
            txtInfo.setText(displayComic.getInfo());
            lblComic.setText("Comic " + (index + 1) + " of " + size);
        } else
        {
            JOptionPane.showMessageDialog(null, "You have reached the end of the list.");
        }


    }//GEN-LAST:event_btnNextComicActionPerformed

    private void btnNextMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextMemberActionPerformed
        
        //to scroll to next member
        
        String MemberID = txtMember.getText();
        int index = RS.getMemberIndex(MemberID);
        index++;
        int size = RS.getSizeOfMember();

        if (index >= size)
        {
            JOptionPane.showMessageDialog(null, "You have reached the end of this list.");
            return;
        }

        Rentee displayMember = RS.searchMemberByIndex(index);

        txtMember.setText(displayMember.getID());
        txtName.setText(displayMember.getName());

        DefaultTableModel tableModel = (DefaultTableModel) tableLoan.getModel();

        tableModel.setRowCount(0);

        for (Comic comic : displayMember.getComicsLoaned())
        {
            Object[] rowData = new Object[4];
            rowData[0] = comic.getISBN();
            rowData[1] = comic.getTitle();
            rowData[2] = comic.getRentalFee();
            rowData[3] = comic.getDepositFee();
            tableModel.addRow(rowData);
        }
        lblRentee.setText("Rentee " + (index + 1) + " of " + size);

    }//GEN-LAST:event_btnNextMemberActionPerformed

    private void btnPreviousMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousMemberActionPerformed
        
        //scroll to previous member
        
        String MemberID = txtMember.getText();
        int index = RS.getMemberIndex(MemberID);
        index--;
        int size = RS.getSizeOfMember();

        if (index < 0)
        {
            JOptionPane.showMessageDialog(null, "You have reached the beginning of this list.");
            return;
        }

        Rentee displayMember = RS.searchMemberByIndex(index);

        txtMember.setText(displayMember.getID());
        txtName.setText(displayMember.getName());

        DefaultTableModel tableModel = (DefaultTableModel) tableLoan.getModel();

        tableModel.setRowCount(0);

        for (Comic comic : displayMember.getComicsLoaned())
        {
            Object[] rowData = new Object[4];
            rowData[0] = comic.getISBN();
            rowData[1] = comic.getTitle();
            rowData[2] = comic.getRentalFee();
            rowData[3] = comic.getDepositFee();
            tableModel.addRow(rowData);
        }
        lblRentee.setText("Rentee " + (index + 1) + " of " + size);
    }//GEN-LAST:event_btnPreviousMemberActionPerformed

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClearActionPerformed
        //clear system message box
        txtMessage.setText("");
    }//GEN-LAST:event_txtClearActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        //get input from search bar
        String Input = txtSearch.getText();

        if (radioISBN.isSelected())
        {   
            //search by ISBN
            Comic ComicFound = RS.SearchBook(Input);

            

            if (ComicFound == null)
            {
                txtMessage.setText("No such ISBN \"" + Input + "\" in the data!");
            } else
            {

                int index = RS.getComicIndex(Input);
                int size = RS.getSizeOfComic();
                index += 1;
                lblComic.setText("Comic " + index + " of " + size);
                txtISBN.setText(ComicFound.getISBN());
                txtTitle.setText(ComicFound.getTitle());
                txtRentalCost.setText(ComicFound.getRentalFee());
                txtDeposit.setText(ComicFound.getDepositFee());
                txtInfo.setText(ComicFound.getInfo());
            }
        } else if (radioMember.isSelected())
        {
            
            //search by memberID
            
            Rentee MemberFound = RS.SearchMember(Input);

            if (MemberFound == null)
            {
                txtMessage.setText("No such Member with the ID of \"" + Input + "\" in the data!");
            } else
            {
                txtMember.setText(MemberFound.getID());
                txtName.setText(MemberFound.getName());
                DefaultTableModel tableModel = (DefaultTableModel) tableLoan.getModel();

                tableModel.setRowCount(0);

                for (Comic comic : MemberFound.getComicsLoaned())
                {
                    Object[] rowData = new Object[4];
                    rowData[0] = comic.getISBN();
                    rowData[1] = comic.getTitle();
                    rowData[2] = comic.getRentalFee();
                    rowData[3] = comic.getDepositFee();
                    tableModel.addRow(rowData);
                }
            }

        } else
        {   
            //if no radio button is selected
            JOptionPane.showMessageDialog(null, "Please choose an option to search!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnPreviousComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousComicActionPerformed

        String ISBN = txtISBN.getText();
        int index = RS.getComicIndex(ISBN);

        int size = RS.getSizeOfComic();
        if (index > 0)
        {
            index--;
            Comic displayComic = RS.searchComicByIndex(index);
            txtISBN.setText(displayComic.getISBN());
            txtTitle.setText(displayComic.getTitle());
            txtRentalCost.setText(displayComic.getRentalFee());
            txtDeposit.setText(displayComic.getDepositFee());
            txtInfo.setText(displayComic.getInfo());
            lblComic.setText("Comic " + (index + 1) + " of " + size);
        } else
        {
            JOptionPane.showMessageDialog(null, "You have reached the beginning of the list.");
        }
    }//GEN-LAST:event_btnPreviousComicActionPerformed

    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsActionPerformed
        txtMessage.setText("");
        txtMessage.setText(RS.calculateTotalEarning());
    }//GEN-LAST:event_btnStatsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        //        //to calculate end time
        long endTime = System.nanoTime();
        long elapsedTime = endTime - startTime;
        long minutes = elapsedTime / 60000000000L;
        long seconds = (elapsedTime % 60000000000L) / 1000000000L;
        JOptionPane.showMessageDialog(null, "Saving data...");
        JOptionPane.showMessageDialog(null, "Thank you for using Comic Rental.\nWe look forward to serve you in the near future.\n\nYou spent a total of " + minutes + " minutes and " + seconds + " seconds in the program.", "Message", JOptionPane.INFORMATION_MESSAGE);
        
        //save rentees into .dat file
        try
        {
            ObjectOutputStream outStream = new ObjectOutputStream(
                    new FileOutputStream("rentees.dat")
            );

            int sizeOfArray = RS.getSizeOfMember();

            for (int i = 0; i < sizeOfArray; i++)
            {

                Rentee memberFound = RS.searchMemberByIndex(i);
                outStream.writeObject(memberFound);
            }

            outStream.close();

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        String Password = "Admin";
        String Admin = JOptionPane.showInputDialog(null, "Password: ");

        if (Admin.equals(Password))
        {
            Admin AD = new Admin();
            AD.setVisible(true);
            dispose();
        } else
        {
            JOptionPane.showMessageDialog(null, "Wrong Password!");
        }


    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RentalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RentalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RentalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RentalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnNextComic;
    private javax.swing.JButton btnNextMember;
    private javax.swing.JButton btnPreviousComic;
    private javax.swing.JButton btnPreviousMember;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnStats;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblComic;
    private javax.swing.JLabel lblRentee;
    private javax.swing.JPanel panelComic;
    private javax.swing.JPanel panelMessage;
    private javax.swing.JPanel panelRentee;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JRadioButton radioISBN;
    private javax.swing.JRadioButton radioMember;
    private javax.swing.JTable tableLoan;
    private javax.swing.JButton txtClear;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtMember;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRentalCost;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
